// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelWithUs.DBContext;

namespace TravelWithUsContextLib.Migrations
{
    [DbContext(typeof(TravelWithUsDbContext))]
    partial class TravelWithUsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExcursionHotel", b =>
                {
                    b.Property<int>("ExcursionesExcursionID")
                        .HasColumnType("int");

                    b.Property<int>("HotelesHotelID")
                        .HasColumnType("int");

                    b.HasKey("ExcursionesExcursionID", "HotelesHotelID");

                    b.HasIndex("HotelesHotelID");

                    b.ToTable("ExcursionHotel");

                    b.HasData(
                        new
                        {
                            ExcursionesExcursionID = 1,
                            HotelesHotelID = 1
                        },
                        new
                        {
                            ExcursionesExcursionID = 2,
                            HotelesHotelID = 2
                        });
                });

            modelBuilder.Entity("FacilidadPaquete", b =>
                {
                    b.Property<int>("FacilidadesFacilidadID")
                        .HasColumnType("int");

                    b.Property<int>("PaquetesCodigo")
                        .HasColumnType("int");

                    b.HasKey("FacilidadesFacilidadID", "PaquetesCodigo");

                    b.HasIndex("PaquetesCodigo");

                    b.ToTable("FacilidadPaquete");
                });

            modelBuilder.Entity("TravelWithUs.Models.Agencia", b =>
                {
                    b.Property<int>("AgenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DescripcionA");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("DireccionA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("EmailA");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumFaxA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("NombreA");

                    b.HasKey("AgenciaID");

                    b.ToTable("Agencia");

                    b.HasData(
                        new
                        {
                            AgenciaID = 1,
                            Descripcion = "Agencia de turismo que le permitira conocer diferentes lugares en toda la isla, con excelentes servicios en hoteles y casas de arrendamiento, asi como alquiler de autos.",
                            Direccion = "Playa",
                            Email = "cubanacan@gmail.com",
                            Fax = "78538964",
                            Nombre = "Cubanacan"
                        },
                        new
                        {
                            AgenciaID = 2,
                            Descripcion = "La Agencia de Viajes gaviota brinda las facilidadesd de conocer maravillosos lugares de Cuba a la vez que disfruta de una agradable estancia. Cuenta con servicio de diferentes aerolíneas , con precios módicos y excelente calidad.",
                            Direccion = "Plaza",
                            Email = "gaviota@gmail.com",
                            Fax = "76885479",
                            Nombre = "Gaviota"
                        },
                        new
                        {
                            AgenciaID = 3,
                            Descripcion = "Agencia especializada en el turismo ecológico. Cuenta con excursiones a verdaderas maravillas naturales de Cuba y hospedajes en lugares en su mayoría rurales , especial para disfrutar de un ambiente sano.",
                            Direccion = "Habana Vieja",
                            Email = "ecocuba@gmail.com",
                            Fax = "72086942",
                            Nombre = "EcoCuba"
                        },
                        new
                        {
                            AgenciaID = 4,
                            Descripcion = " Agencia cubana que cuenta con mas de 200 sitios turísticos para visitar en Cuba en su catálogo , la mayoría de estos con estrecha relación con otros países del caribe y América Latina. ",
                            Direccion = "Playa",
                            Email = "caribe@gmail.com",
                            Fax = "72028546",
                            Nombre = "CaribeTour"
                        },
                        new
                        {
                            AgenciaID = 5,
                            Descripcion = " Agencia cubana creada hace poco mas de dos años que en su catálogo muestra diversas opciones encaminadas principalmente al publico joven. ",
                            Direccion = "Vedado",
                            Email = "cubaviaje@gmail.com",
                            Fax = "72028642",
                            Nombre = "CubaViaje"
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Excursion", b =>
                {
                    b.Property<int>("ExcursionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdE")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DescripcionE");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaLlegadaE");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaSalidaE");

                    b.Property<string>("LugarLlegada")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("LugarLlegadaE");

                    b.Property<string>("LugarSalida")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("LugarSalidaE");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ExcursionID");

                    b.ToTable("Excursion");

                    b.HasData(
                        new
                        {
                            ExcursionID = 1,
                            Descripcion = "A unos 12 km de Matanzas, Cuba en dirección Varadero se encuentra una gruta a la que aflora un lago de aguas cristalinas conocida con el nombre de Cueva Saturno. Se observan abundantes estalagmitas y estalactitas. El lago tiene una profundidad de 18 metros pero sus aguas son de una transparencia tan increíble que permiten ver el fondo sin dificultad alguna.",
                            FechaLlegada = new DateTime(2021, 6, 6, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2021, 6, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarLlegada = "Cuevas de  Saturno",
                            LugarSalida = "Parque Normal",
                            Precio = 17m
                        },
                        new
                        {
                            ExcursionID = 2,
                            Descripcion = "Está ubicado en la provincia de Pinar del Río, zona más occidental de Cuba, exactamente en el grupo montañoso de la Cordillera de Guaniguanico. Este Valle y gran parte de la sierra que lo rodea fue aprobado en 1999 como Parque Nacional y, en diciembre de ese mismo año, fue declarado por la UNESCO Patrimonio de la Humanidad, en la categoría de Paisaje Cultural. Posee además la condición de Monumento Nacional.",
                            FechaLlegada = new DateTime(2021, 7, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2021, 7, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarLlegada = "valle de Viñales",
                            LugarSalida = "Parque Normal",
                            Precio = 25m
                        },
                        new
                        {
                            ExcursionID = 3,
                            Descripcion = "Con unos 30 kilómetros de largo, de los que 22 son playas, Varadero está considerado, por su perenne luz tropical, su exótica y exuberante vegetación y la calidad de sus aguas, uno de los principales atractivos para los viajeros de todo el mundo. La Playa de Varadero, o Playa Azul, hermosísimo enclave de arena rosa y blanca y agua cristalina, es una de las playas más espectaculares del mundo. Y, sin duda, la más bella de toda Cuba",
                            FechaLlegada = new DateTime(2021, 8, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2021, 8, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarLlegada = "Varadero",
                            LugarSalida = "Parque Normal",
                            Precio = 40m
                        },
                        new
                        {
                            ExcursionID = 4,
                            Descripcion = "Las Terrazas es una pequeña comunidad turística rural de desarrollo sostenible que te ofrece un entorno único en el conectar con la naturaleza. Situada a 75 kilómetros al oeste de La Habana, este lugar forma parte de la Sierra del Rosario, catalogada por la UNESCO como Reserva de la Biosfera en 1985.",
                            FechaLlegada = new DateTime(2021, 8, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2021, 8, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarLlegada = "Las Terrazas",
                            LugarSalida = "Parque Normal",
                            Precio = 40m
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Facilidad", b =>
                {
                    b.Property<int>("FacilidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdF")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("DescripcionF");

                    b.HasKey("FacilidadID");

                    b.ToTable("Facilidades");

                    b.HasData(
                        new
                        {
                            FacilidadID = 1,
                            Descripcion = "todo incluido"
                        },
                        new
                        {
                            FacilidadID = 2,
                            Descripcion = "mesa buffet"
                        },
                        new
                        {
                            FacilidadID = 3,
                            Descripcion = "piscina interior, spa"
                        },
                        new
                        {
                            FacilidadID = 4,
                            Descripcion = "gimnasio, sala de juegos"
                        },
                        new
                        {
                            FacilidadID = 5,
                            Descripcion = "servicio de taxi"
                        },
                        new
                        {
                            FacilidadID = 6,
                            Descripcion = "servicio de internet"
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaH");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DescripcionH");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("DireccionH");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("NombreH");

                    b.HasKey("HotelID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            HotelID = 1,
                            Categoria = 3,
                            Descripcion = "Meliá Cohiba ofrece espectaculares vistas sobre el mar y la ciudad. Un excepcional hotel para viajes de placer o negocios que destaca por su ubicación, su exclusivo servicio The Level y su animada sala de fiestas.",
                            Direccion = "Plaza",
                            Nombre = "Melia Cohiba"
                        },
                        new
                        {
                            HotelID = 2,
                            Categoria = 5,
                            Descripcion = "Este hotel de lujo con todo incluido tiene un impresionante vestíbulo circular con vistas al mar y está a 1,4 km del Varadero Golf Club y a 9 km de la Península de Hicacos.",
                            Direccion = "Habana Vieja",
                            Nombre = "Varadero"
                        },
                        new
                        {
                            HotelID = 3,
                            Categoria = 5,
                            Descripcion = "Hotel 4 estrellas, ubicado en la zona residencial de Miramar, donde se encuentran la mayoría de embajadas y firmas comerciales. Dispone de amplias habitaciones, una espectacular piscina, una completa oferta gastronómica, el servicio Privilege Exclusive Rooms and Services y tres salones de reuniones. Recomendado para viajes de negocios, grupos, parejas.",
                            Direccion = "Habana Vieja",
                            Nombre = "Panorama"
                        },
                        new
                        {
                            HotelID = 4,
                            Categoria = 4,
                            Descripcion = "Hotel Nacional es una magnífica elección para los viajeros que visiten La Habana, ya que ofrece un ambiente elegante, además de numerosos servicios diseñados para mejorar tu estancia. Al estar cerca de los puntos de referencia más conocidos de La Habana es un magnífico destino para turistas.",
                            Direccion = "Plaza",
                            Nombre = "Hotel Nacional"
                        },
                        new
                        {
                            HotelID = 5,
                            Categoria = 3,
                            Descripcion = "El hotel 5 Estrellas Tryp Habana Libre, uno de los más emblemáticos de La Habana, está localizado en el corazón del Vedado. El hotel, con una altura majestuosa de 25 plantas y 572 habitaciones, ofrece impresionantes vistas de la ciudad y el mar. Ideal para hombres de negocios, eventos, vacaciones y lunas de miel.",
                            Direccion = "Plaza",
                            Nombre = "Habana Libre"
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Oferta", b =>
                {
                    b.Property<int>("OfertaID")
                        .HasColumnType("int")
                        .HasColumnName("IdO");

                    b.Property<int>("HotelID")
                        .HasColumnType("int")
                        .HasColumnName("IdH");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("DescripcionO");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("OfertaID", "HotelID");

                    b.HasIndex("HotelID");

                    b.ToTable("Ofertas");

                    b.HasData(
                        new
                        {
                            OfertaID = 1,
                            HotelID = 1,
                            Descripcion = "Habitación para dos personas con cama matrimonial para una excelente velada romántica. Baño con jacuzzy con sales arómaticas ",
                            Precio = 75m
                        },
                        new
                        {
                            OfertaID = 2,
                            HotelID = 1,
                            Descripcion = "Habitación para una persona con servicio a la habitacion ",
                            Precio = 30m
                        },
                        new
                        {
                            OfertaID = 3,
                            HotelID = 1,
                            Descripcion = "Habitación para dos personas . Baño con jacuzzy con sales arómaticas ",
                            Precio = 60m
                        },
                        new
                        {
                            OfertaID = 1,
                            HotelID = 2,
                            Descripcion = "Habitación para familia.Servicio de habiatcion ",
                            Precio = 100m
                        },
                        new
                        {
                            OfertaID = 2,
                            HotelID = 2,
                            Descripcion = "Oferta para un dia con derecho a habitacion y piscina.",
                            Precio = 20m
                        },
                        new
                        {
                            OfertaID = 3,
                            HotelID = 2,
                            Descripcion = "Fin de semana exclusivo ",
                            Precio = 150m
                        },
                        new
                        {
                            OfertaID = 1,
                            HotelID = 3,
                            Descripcion = "Habitación para dos personas . Baño con jacuzzy con sales arómaticas ",
                            Precio = 60m
                        },
                        new
                        {
                            OfertaID = 2,
                            HotelID = 3,
                            Descripcion = "Habitación familiar para un dia y una noche con servivio d spa. ",
                            Precio = 100m
                        },
                        new
                        {
                            OfertaID = 3,
                            HotelID = 3,
                            Descripcion = "Habitación para una persona con servicio a la habitacion ",
                            Precio = 40m
                        },
                        new
                        {
                            OfertaID = 2,
                            HotelID = 4,
                            Descripcion = "Fin de semana romantico ,para parejas de aniversario con descuento. ",
                            Precio = 80m
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Paquete", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodigoP")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("DescripcionP");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time")
                        .HasColumnName("DuracionP");

                    b.Property<int>("ExcursionID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("ExcursionID");

                    b.ToTable("Paquete");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descripcion = "Viaje maritimo",
                            Duracion = new TimeSpan(0, 5, 10, 4, 0),
                            ExcursionID = 1,
                            Precio = 75m
                        },
                        new
                        {
                            Codigo = 2,
                            Descripcion = "Viaje rural",
                            Duracion = new TimeSpan(0, 3, 10, 4, 0),
                            ExcursionID = 2,
                            Precio = 50m
                        },
                        new
                        {
                            Codigo = 3,
                            Descripcion = "Viaje a zona de playa ",
                            Duracion = new TimeSpan(0, 2, 10, 4, 0),
                            ExcursionID = 1,
                            Precio = 100m
                        },
                        new
                        {
                            Codigo = 4,
                            Descripcion = "Viaje a lugares historicos",
                            Duracion = new TimeSpan(0, 7, 10, 5, 0),
                            ExcursionID = 1,
                            Precio = 60m
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaExcursion", b =>
                {
                    b.Property<int>("AgenciaID")
                        .HasColumnType("int")
                        .HasColumnName("IdA");

                    b.Property<int>("ExcursionID")
                        .HasColumnType("int")
                        .HasColumnName("IdE");

                    b.Property<int>("TuristaID")
                        .HasColumnType("int")
                        .HasColumnName("IdT");

                    b.HasKey("AgenciaID", "ExcursionID", "TuristaID");

                    b.HasIndex("ExcursionID");

                    b.HasIndex("TuristaID");

                    b.ToTable("ReservasExcursiones");

                    b.HasData(
                        new
                        {
                            AgenciaID = 2,
                            ExcursionID = 1,
                            TuristaID = 7
                        },
                        new
                        {
                            AgenciaID = 5,
                            ExcursionID = 1,
                            TuristaID = 5
                        },
                        new
                        {
                            AgenciaID = 1,
                            ExcursionID = 1,
                            TuristaID = 4
                        },
                        new
                        {
                            AgenciaID = 2,
                            ExcursionID = 2,
                            TuristaID = 1
                        },
                        new
                        {
                            AgenciaID = 2,
                            ExcursionID = 1,
                            TuristaID = 9
                        },
                        new
                        {
                            AgenciaID = 2,
                            ExcursionID = 4,
                            TuristaID = 6
                        },
                        new
                        {
                            AgenciaID = 3,
                            ExcursionID = 3,
                            TuristaID = 2
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaIndividual", b =>
                {
                    b.Property<int>("ReservaIndividualID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRI")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgenciaID")
                        .HasColumnType("int")
                        .HasColumnName("IdA");

                    b.Property<int>("HotelID")
                        .HasColumnType("int")
                        .HasColumnName("IdH");

                    b.Property<int>("OfertaID")
                        .HasColumnType("int")
                        .HasColumnName("IdO");

                    b.Property<int>("TuristaID")
                        .HasColumnType("int")
                        .HasColumnName("IdT");

                    b.Property<int>("Acompanantes")
                        .HasColumnType("int")
                        .HasColumnName("NumAcompanantes");

                    b.Property<string>("Aerolinea")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("CompAereaRI");

                    b.Property<DateTime>("Llegada")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaLlegadaH");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaSalidaH");

                    b.HasKey("ReservaIndividualID", "AgenciaID", "HotelID", "OfertaID", "TuristaID");

                    b.HasIndex("AgenciaID");

                    b.HasIndex("TuristaID");

                    b.HasIndex("OfertaID", "HotelID");

                    b.ToTable("ReservasIndividuales");

                    b.HasData(
                        new
                        {
                            ReservaIndividualID = 1,
                            AgenciaID = 2,
                            HotelID = 1,
                            OfertaID = 1,
                            TuristaID = 7,
                            Acompanantes = 1,
                            Llegada = new DateTime(2021, 7, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 30m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 2,
                            AgenciaID = 2,
                            HotelID = 1,
                            OfertaID = 3,
                            TuristaID = 2,
                            Acompanantes = 2,
                            Llegada = new DateTime(2021, 7, 10, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 40m,
                            Salida = new DateTime(2021, 10, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 3,
                            AgenciaID = 1,
                            HotelID = 3,
                            OfertaID = 1,
                            TuristaID = 3,
                            Acompanantes = 0,
                            Llegada = new DateTime(2021, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 20m,
                            Salida = new DateTime(2021, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 4,
                            AgenciaID = 5,
                            HotelID = 4,
                            OfertaID = 2,
                            TuristaID = 2,
                            Acompanantes = 1,
                            Llegada = new DateTime(2021, 12, 10, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 50m,
                            Salida = new DateTime(2021, 12, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 5,
                            AgenciaID = 2,
                            HotelID = 1,
                            OfertaID = 2,
                            TuristaID = 7,
                            Acompanantes = 1,
                            Llegada = new DateTime(2021, 7, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 30m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 6,
                            AgenciaID = 3,
                            HotelID = 2,
                            OfertaID = 3,
                            TuristaID = 8,
                            Acompanantes = 5,
                            Llegada = new DateTime(2021, 7, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 30m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReservaIndividualID = 7,
                            AgenciaID = 3,
                            HotelID = 3,
                            OfertaID = 3,
                            TuristaID = 2,
                            Acompanantes = 5,
                            Llegada = new DateTime(2021, 7, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 30m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaPaquete", b =>
                {
                    b.Property<int>("AgenciaID")
                        .HasColumnType("int")
                        .HasColumnName("IdA");

                    b.Property<int>("TuristaID")
                        .HasColumnType("int")
                        .HasColumnName("IdT");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CodigoP");

                    b.Property<string>("Aerolinea")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("CompAereaRP");

                    b.Property<int>("Participantes")
                        .HasColumnType("int")
                        .HasColumnName("CantParticipantes");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaSalidaRP");

                    b.HasKey("AgenciaID", "TuristaID", "Codigo");

                    b.HasIndex("Codigo");

                    b.HasIndex("TuristaID");

                    b.ToTable("ReservasPaquetes");

                    b.HasData(
                        new
                        {
                            AgenciaID = 2,
                            TuristaID = 7,
                            Codigo = 1,
                            Participantes = 2,
                            Precio = 30.00m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 2,
                            TuristaID = 2,
                            Codigo = 1,
                            Participantes = 4,
                            Precio = 40.00m,
                            Salida = new DateTime(2021, 10, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 1,
                            TuristaID = 3,
                            Codigo = 3,
                            Participantes = 2,
                            Precio = 20.00m,
                            Salida = new DateTime(2021, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 5,
                            TuristaID = 2,
                            Codigo = 4,
                            Participantes = 5,
                            Precio = 50.00m,
                            Salida = new DateTime(2021, 12, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 2,
                            TuristaID = 1,
                            Codigo = 1,
                            Participantes = 10,
                            Precio = 30.00m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 3,
                            TuristaID = 8,
                            Codigo = 2,
                            Participantes = 4,
                            Precio = 30.00m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AgenciaID = 3,
                            TuristaID = 9,
                            Codigo = 2,
                            Participantes = 5,
                            Precio = 40.00m,
                            Salida = new DateTime(2021, 10, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TravelWithUs.Models.Turista", b =>
                {
                    b.Property<int>("TuristaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("EmailT");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NacionalidadT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NombreT");

                    b.HasKey("TuristaID");

                    b.ToTable("Turistas");

                    b.HasData(
                        new
                        {
                            TuristaID = 1,
                            Email = "juan@travelwithus.com",
                            Nacionalidad = "España",
                            Nombre = "Juan Gonzalez"
                        },
                        new
                        {
                            TuristaID = 2,
                            Email = "luci@travelwithus.com",
                            Nacionalidad = "China",
                            Nombre = "Luci Wong"
                        },
                        new
                        {
                            TuristaID = 3,
                            Email = "clear@travelwithus.com",
                            Nacionalidad = "Alemania",
                            Nombre = "Clear Yort"
                        },
                        new
                        {
                            TuristaID = 4,
                            Email = "arman@travelwithus.com",
                            Nacionalidad = "Mexico",
                            Nombre = "Armando Perez"
                        },
                        new
                        {
                            TuristaID = 5,
                            Email = "perez@travelwithus.com",
                            Nacionalidad = "Panama",
                            Nombre = "Hector Perez"
                        },
                        new
                        {
                            TuristaID = 6,
                            Email = "perez25@travelwithus.com",
                            Nacionalidad = "Panama",
                            Nombre = "Lidia Perez"
                        },
                        new
                        {
                            TuristaID = 7,
                            Email = "smith@travelwithus.com",
                            Nacionalidad = "Canada",
                            Nombre = "Jhon Smith"
                        },
                        new
                        {
                            TuristaID = 8,
                            Email = "li@travelwithus.com",
                            Nacionalidad = "Japon",
                            Nombre = "Hissake Li"
                        },
                        new
                        {
                            TuristaID = 9,
                            Email = "yen@travelwithus.com",
                            Nacionalidad = "japon",
                            Nombre = "Yen Gij"
                        },
                        new
                        {
                            TuristaID = 10,
                            Email = "ruz@travelwithus.com",
                            Nacionalidad = "Suecia",
                            Nombre = "Liana Ruz"
                        });
                });

            modelBuilder.Entity("ExcursionHotel", b =>
                {
                    b.HasOne("TravelWithUs.Models.Excursion", null)
                        .WithMany()
                        .HasForeignKey("ExcursionesExcursionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelesHotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilidadPaquete", b =>
                {
                    b.HasOne("TravelWithUs.Models.Facilidad", null)
                        .WithMany()
                        .HasForeignKey("FacilidadesFacilidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Paquete", null)
                        .WithMany()
                        .HasForeignKey("PaquetesCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelWithUs.Models.Oferta", b =>
                {
                    b.HasOne("TravelWithUs.Models.Hotel", "Hotel")
                        .WithMany("Ofertas")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelWithUs.Models.Paquete", b =>
                {
                    b.HasOne("TravelWithUs.Models.Excursion", "Excursion")
                        .WithMany("Paquetes")
                        .HasForeignKey("ExcursionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excursion");
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaExcursion", b =>
                {
                    b.HasOne("TravelWithUs.Models.Agencia", "Agencia")
                        .WithMany("ReservasExcursiones")
                        .HasForeignKey("AgenciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Excursion", "Excursion")
                        .WithMany("ReservasExcursiones")
                        .HasForeignKey("ExcursionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Turista", "Turista")
                        .WithMany("ReservasExcursiones")
                        .HasForeignKey("TuristaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Excursion");

                    b.Navigation("Turista");
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaIndividual", b =>
                {
                    b.HasOne("TravelWithUs.Models.Agencia", "Agencia")
                        .WithMany("ReservasIndividuales")
                        .HasForeignKey("AgenciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Turista", "Turista")
                        .WithMany("ReservasIndividuales")
                        .HasForeignKey("TuristaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Oferta", "Oferta")
                        .WithMany("ReservasIndividuales")
                        .HasForeignKey("OfertaID", "HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Oferta");

                    b.Navigation("Turista");
                });

            modelBuilder.Entity("TravelWithUs.Models.ReservaPaquete", b =>
                {
                    b.HasOne("TravelWithUs.Models.Agencia", "Agencia")
                        .WithMany("ReservasPaquetes")
                        .HasForeignKey("AgenciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Paquete", "Paquete")
                        .WithMany("ReservasPaquetes")
                        .HasForeignKey("Codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWithUs.Models.Turista", "Turista")
                        .WithMany("ReservasPaquetes")
                        .HasForeignKey("TuristaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Paquete");

                    b.Navigation("Turista");
                });

            modelBuilder.Entity("TravelWithUs.Models.Agencia", b =>
                {
                    b.Navigation("ReservasExcursiones");

                    b.Navigation("ReservasIndividuales");

                    b.Navigation("ReservasPaquetes");
                });

            modelBuilder.Entity("TravelWithUs.Models.Excursion", b =>
                {
                    b.Navigation("Paquetes");

                    b.Navigation("ReservasExcursiones");
                });

            modelBuilder.Entity("TravelWithUs.Models.Hotel", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("TravelWithUs.Models.Oferta", b =>
                {
                    b.Navigation("ReservasIndividuales");
                });

            modelBuilder.Entity("TravelWithUs.Models.Paquete", b =>
                {
                    b.Navigation("ReservasPaquetes");
                });

            modelBuilder.Entity("TravelWithUs.Models.Turista", b =>
                {
                    b.Navigation("ReservasExcursiones");

                    b.Navigation("ReservasIndividuales");

                    b.Navigation("ReservasPaquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
